# Generated by Django 5.1.2 on 2025-03-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
